services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: 1234567890123456789012345678901a
      - key: N8N_HOST
        value: n8n-render-h4tx.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-render-h4tx.onrender.com/
    ports:
      - port: 5678
        protocol: HTTP
